branch-defaults:
  default:
    environment: tutorials-4bphk-env
  master:
    environment: tutorials-4bphk-env
environment-defaults:
  tutorials-4bphk-env:
    branch: master
    repository: eb-nodejs-test
global:
  application_name: tutorials
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-2::platform/Node.js running on
    64bit Amazon Linux/4.3.0
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
